name: Artifact Download and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Working Directory
      run: |
        # Create a directory to store files
        mkdir workingdirectory
        echo "hello" > workingdirectory/hello.html
        echo "world" > workingdirectory/world.html

    - name: Create Artifacts Directory
      run: |
        # Create a directory to store artifacts
        mkdir artifactsdirectory

    - name: Copy Files to Artifacts Directory
      run: |
        # Copy files from workingdirectory to artifactsdirectory
        cp -r workingdirectory/* artifactsdirectory/

    - name: List Artifacts Directory
      run: |
        # List the contents of the artifacts directory
        ls artifactsdirectory/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: artifactsdirectory

        
  download_artifact:
              needs: build
              runs-on: ubuntu-latest
          
              steps:
              - name: Checkout code
                uses: actions/checkout@v2
          
              - name: Download Artifacts
                uses: actions/download-artifact@v2
                with:
                  name: my-artifacts  # The name of the artifact to download
          
         #     - name: List Downloaded Artifacts
         #       run: |
         #         # List the contents of the downloaded artifacts directory
         #         ls ${{ github.workspace }}/my-artifacts
         # 
         #     # Add more steps to process or use the downloaded artifacts
          
