name: secrets
run-name: using the secret variables

on: [push]

jobs:
     secret-job:
              name: secret variables
              runs-on: ubuntu-latest
              steps:
                 - name: using the first secret variable
                   run:  echo " ${{ secrets.AWS_ACCESS_KEY_ID }}"
                 - name: using the second secret variable
                   run:  echo " ${{secrets.AWS_SECRET_ACCESS_KEY}}
               
